import { useNavigate } from "react-router-dom"

const LAST_UPDATED = "May 1, 2026"
const COMPANY = "Orbis Technologies, Inc."
const EMAIL = "legal@orbis.app"

const sections = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content: `By accessing or using Orbis (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, do not access or use the Service. These Terms apply to all visitors, users, and others who access or use the Service. Your continued use of the Service after any changes to these Terms constitutes acceptance of those changes.`,
  },
  {
    id: "description",
    title: "2. Description of Service",
    content: `Orbis provides an AI-powered stock market scanning and trading tools platform designed to help independent traders identify potential breakout opportunities using quantitative analysis. The Service includes a stock scanner, AI-assisted analysis, portfolio tracking, brokerage connectivity via SnapTrade, and related features.

IMPORTANT: Orbis is a technology and data platform only. Nothing on the Service constitutes financial, investment, legal, or tax advice. All market data, analysis, and signals generated by the Service are for informational and educational purposes only. Trading stocks and other securities involves substantial risk of loss, and past performance is not indicative of future results. You are solely responsible for your own investment decisions.`,
  },
  {
    id: "accounts",
    title: "3. User Accounts",
    content: `To access certain features of the Service, you must create an account. You agree to: (a) provide accurate, current, and complete information during registration; (b) maintain and promptly update your account information; (c) keep your password confidential and not share it with any third party; (d) notify us immediately at ${EMAIL} if you suspect any unauthorized use of your account; and (e) accept responsibility for all activities that occur under your account.

You must be at least 18 years of age to create an account. We reserve the right to suspend or terminate any account that violates these Terms or that we determine, in our sole discretion, poses a risk to the Service or other users.`,
  },
  {
    id: "subscriptions",
    title: "4. Subscription Plans",
    content: `Orbis offers two paid subscription plans:

Core Plan — $39.00 per month. Includes access to the stock scanner, basic AI insights, portfolio tracking, and standard brokerage connectivity.

Premium Plan — $79.00 per month. Includes all Core features plus advanced AI analysis, priority data updates, expanded scanner capabilities, and premium support.

All plans include a 7-day free trial for new subscribers. No credit card charge occurs during the trial period. At the end of the trial, your selected plan will automatically activate and your payment method will be charged unless you cancel before the trial ends.

Plan features, pricing, and availability are subject to change. We will provide at least 30 days' notice before any price increase takes effect for existing subscribers.`,
  },
  {
    id: "billing",
    title: "5. Payment and Billing",
    content: `Subscriptions are billed monthly on a recurring basis through Stripe, our third-party payment processor. By providing a payment method, you authorize us to charge the applicable subscription fee each month until you cancel.

You represent that you are authorized to use the payment method provided and that the billing information you supply is accurate. All fees are quoted and charged in U.S. dollars. Taxes may apply depending on your location.

If a payment fails, we will attempt to retry the charge. If payment cannot be processed after reasonable attempts, your access to paid features may be suspended until payment is resolved. We are not responsible for any overdraft fees or other charges your bank or card issuer may impose.

We do not store your full payment card number. Card data is handled directly by Stripe and subject to their privacy and security practices.`,
  },
  {
    id: "cancellation",
    title: "6. Cancellation and Refunds",
    content: `You may cancel your subscription at any time from your account settings. Cancellation takes effect at the end of your current billing period. You will retain access to paid features until that date.

Orbis does not offer refunds for partial billing periods. If you cancel during a free trial, you will not be charged. If you believe you were charged in error, contact us at ${EMAIL} within 30 days and we will investigate.

We reserve the right to cancel or suspend accounts that violate these Terms. In the event of termination for cause, no refund will be issued.`,
  },
  {
    id: "ip",
    title: "7. Intellectual Property",
    content: `The Service and its original content, features, functionality, branding, design, software, and algorithms are and will remain the exclusive property of ${COMPANY} and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without our prior written consent.

Market data displayed on the Service is provided by third-party data providers including Polygon.io and is subject to their respective terms and licenses. You may not scrape, harvest, copy, or redistribute any market data obtained through the Service except as expressly permitted.

User-generated content (such as notes, watchlists, or custom filters) remains your property. By using the Service, you grant us a limited, non-exclusive license to store and process that content solely to provide the Service to you.`,
  },
  {
    id: "prohibited",
    title: "8. Prohibited Uses",
    content: `You agree not to use the Service to: (a) violate any applicable law or regulation; (b) engage in market manipulation, insider trading, or other securities fraud; (c) reverse-engineer, decompile, or attempt to extract the source code of the Service; (d) scrape, crawl, or use automated means to access or collect data from the Service without our written permission; (e) resell or redistribute the Service or data obtained from it; (f) upload or transmit viruses, malware, or other malicious code; (g) attempt to gain unauthorized access to any part of the Service or its related systems; (h) use the Service to harass, threaten, or harm any person; or (i) impersonate any person or entity or misrepresent your affiliation.`,
  },
  {
    id: "disclaimer",
    title: "9. Disclaimer — Not Financial Advice",
    content: `THE SERVICE IS PROVIDED FOR INFORMATIONAL AND EDUCATIONAL PURPOSES ONLY. ORBIS IS NOT A REGISTERED INVESTMENT ADVISOR, BROKER-DEALER, OR FINANCIAL PLANNER. NOTHING ON THE SERVICE CONSTITUTES FINANCIAL, INVESTMENT, LEGAL, OR TAX ADVICE.

ALL ANALYSIS, SIGNALS, SCORES, RECOMMENDATIONS, AND OTHER OUTPUTS GENERATED BY THE SERVICE (INCLUDING AI-GENERATED CONTENT) ARE FOR GENERAL INFORMATIONAL PURPOSES ONLY AND SHOULD NOT BE RELIED UPON AS THE BASIS FOR ANY INVESTMENT DECISION.

TRADING STOCKS, OPTIONS, AND OTHER SECURITIES INVOLVES SUBSTANTIAL RISK OF LOSS. PAST PERFORMANCE IS NOT INDICATIVE OF FUTURE RESULTS. YOU COULD LOSE ALL OF YOUR INVESTED CAPITAL. YOU SHOULD CONSULT A LICENSED FINANCIAL ADVISOR BEFORE MAKING ANY INVESTMENT DECISIONS.`,
  },
  {
    id: "warranty",
    title: "10. Disclaimer of Warranties",
    content: `THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR UNINTERRUPTED OR ERROR-FREE OPERATION.

We do not warrant that: (a) the Service will be uninterrupted, secure, or error-free; (b) market data or analysis will be accurate, complete, or timely; (c) any defects will be corrected; or (d) the Service or the servers that make it available are free of viruses or other harmful components.`,
  },
  {
    id: "liability",
    title: "11. Limitation of Liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL ${COMPANY.toUpperCase()}, ITS OFFICERS, DIRECTORS, EMPLOYEES, AFFILIATES, AGENTS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, LOSS OF DATA, LOSS OF GOODWILL, TRADING LOSSES, OR BUSINESS INTERRUPTION, ARISING OUT OF OR RELATING TO YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

OUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE GREATER OF: (A) THE TOTAL AMOUNTS PAID BY YOU TO ORBIS IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM; OR (B) ONE HUNDRED DOLLARS ($100).`,
  },
  {
    id: "indemnification",
    title: "12. Indemnification",
    content: `You agree to indemnify, defend, and hold harmless ${COMPANY}, its officers, directors, employees, agents, and licensors from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any third-party rights; or (d) any claim that your use of the Service caused damage to a third party.`,
  },
  {
    id: "governing-law",
    title: "13. Governing Law and Disputes",
    content: `These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.

Any dispute arising from or relating to these Terms or the Service shall first be attempted to be resolved through good-faith negotiation. If that fails, disputes shall be resolved by binding arbitration under the rules of the American Arbitration Association, conducted in Delaware. You waive any right to participate in a class action lawsuit or class-wide arbitration.

Notwithstanding the above, either party may seek injunctive or other equitable relief in any court of competent jurisdiction to prevent infringement of intellectual property rights.`,
  },
  {
    id: "changes",
    title: "14. Changes to These Terms",
    content: `We reserve the right to modify these Terms at any time. We will notify you of material changes by posting the updated Terms on this page with a new "Last Updated" date and, for significant changes, by sending an email to your registered address. Your continued use of the Service after such changes constitutes your acceptance of the new Terms.`,
  },
  {
    id: "termination",
    title: "15. Termination",
    content: `We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason, including if you breach these Terms. Upon termination, your right to use the Service will cease. All provisions of these Terms that by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, indemnity, and limitations of liability.`,
  },
  {
    id: "contact",
    title: "16. Contact Us",
    content: `If you have any questions about these Terms of Service, please contact us at:

${COMPANY}
Email: ${EMAIL}

We aim to respond to all inquiries within 5 business days.`,
  },
]

export default function TermsPage() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Background grid */}
      <div className="fixed inset-0 pointer-events-none">
        <div
          className="absolute inset-0 opacity-[0.04]"
          style={{
            backgroundImage:
              "linear-gradient(to right, #00ff88 1px, transparent 1px), linear-gradient(to bottom, #00ff88 1px, transparent 1px)",
            backgroundSize: "80px 80px",
          }}
        />
      </div>

      <div className="relative mx-auto max-w-4xl px-4 sm:px-6 py-24">
        <button
          onClick={() => navigate("/")}
          className="mb-12 font-mono text-xs uppercase tracking-wider text-white/40 hover:text-[#00ff88] transition-colors"
        >
          ← Back to Home
        </button>

        {/* Header */}
        <div className="mb-16">
          <div className="flex items-center gap-2 mb-4">
            <div className="h-px w-8 bg-[#00ff88]" />
            <span className="font-mono text-xs uppercase tracking-wider text-[#00ff88]">Legal</span>
            <div className="h-px w-8 bg-[#00ff88]" />
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold mb-4">Terms of Service</h1>
          <p className="font-mono text-sm text-white/40">Last Updated: {LAST_UPDATED}</p>
          <div className="mt-6 border-l-2 border-[#00ff88]/40 pl-4">
            <p className="font-mono text-sm text-white/60 leading-relaxed">
              Please read these Terms of Service carefully before using Orbis. By accessing or using our platform,
              you agree to be bound by these terms.
            </p>
          </div>
        </div>

        {/* Sections */}
        <div className="space-y-12">
          {sections.map((section) => (
            <div key={section.id} id={section.id} className="border-b border-[#1a1a1a] pb-12">
              <h2 className="font-mono text-lg font-bold text-white mb-4">{section.title}</h2>
              <div className="space-y-4">
                {section.content.split("\n\n").map((para, i) => (
                  <p
                    key={i}
                    className={`font-mono text-sm leading-relaxed ${
                      para === para.toUpperCase() && para.length > 50
                        ? "text-white/50 text-xs"
                        : "text-white/70"
                    }`}
                  >
                    {para}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Footer note */}
        <div className="mt-16 border border-[#00ff88]/20 bg-[#00ff88]/5 p-6">
          <p className="font-mono text-xs text-white/60 text-center">
            Questions about these terms? Contact us at{" "}
            <a href={`mailto:${EMAIL}`} className="text-[#00ff88] hover:underline">
              {EMAIL}
            </a>
          </p>
        </div>
      </div>
    </div>
  )
}
